### PR TITLE
Compare in 2 steps, first with hashcode and for hits use equals

### PR DESCRIPTION
**Pull request by Tasteful**
Speed up comparison of large lists with usage of hash-code.

3.0.0 version
image

3.0.1 version
image

and with changes in this PR
image

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
Looks promising.  I still need some time to wrap my head around the HashSet and how it works.

Also I don't like the EqualityComparison overwrite.
Does that translate into an expression equivalent to EqualityComparison?
I wonder if you can translate the expression `(dto, entity) => dto.ID == entity.ID` to the same result as `source => source.ID, dest => dest.ID` by looking and seeing if there are only equals and ands.  If not default back to original, but if can translate use hashes in list update management.

**Comment by Tasteful** [comment]
It creates 2 different expression/func

1. Fetch the GetHashCode() for all MemberExpression that is used to create a lookup-table.
2. Compare the properties (in the order they are returned) for all MemberExpression.

The hashcode for an object is not mandatory to be unique, that's the reason to first build up an lookup-table. When a hit is in the lookup-table all destination entities that have that hashcode will be executed for the equality comparison to find a match.

It is probably possible to fetch the member expression out from the regular expression `(dto, entity) => dto.ID == entity.ID` but I think it will be harder to get correct expression out, need also to work with `(dto, entity) => dto.ID.Equals(entity.ID)` and a lot of other combinations, example different equals with different string comparisons.

I have the following equalitycomparison that I'm not sure how it will work or if that is possible to map with the new method.
```
               .EqualityComparison((a, b) => a.RelationshipTypeSystemId == b.RelationshipTypeSystemId &&
                                              (a is BaseProductToBaseProductRelationshipLink && ((BaseProductToBaseProductRelationshipLink)a).BaseProductSystemId == b.ToSystemId
                                               || a is BaseProductToCategoryRelationshipLink && ((BaseProductToCategoryRelationshipLink)a).CategorySystemId == b.ToSystemId
                                               || a is BaseProductToVariantRelationshipLink && ((BaseProductToVariantRelationshipLink)a).VariantSystemId == b.ToSystemId))
```

**Comment by TylerCarlson1** [comment]
I could handle or's in that situation I think, since one side of the equals is consistant.  Don't know about more complicated scenarios though.

I would think the equivalent code for GetHashSet_Object would look something like this
```
EqalityComparison(
    a => new { id = a.RelationshipTypeSystemId,
               linkId = ((a as BaseProductToBaseProductRelationshipLink)?.BaseProductSystemId ?? 0) | 
                        ((a as BaseProductToCategoryRelationshipLink)?.CategorySystemId ?? 0) | 
                        ((a as BaseProductToVariantRelationshipLink)?.VariantSystemId ?? 0) },
    b => new { id = b.RelationshipTypeSystemId, 
               linkId = b.ToSystemId})
```

**Comment by TylerCarlson1** [comment]
OK I see what's going on now.  I think is well worth caching a hash code of sorts.

I would still like to infer a hash code from the expression itself for a variety of reasons.
1: API doesn't change, so people don't have to modify code to get the benefit.
2: For AM.Collections.EF and other solutions that generate expressions, this will benefit them as well.
3: Not 2 sets of code to maintain for doing the same thing of generating expressions. (The code for equality comparer expression doesn't look EF/ORM friendly)

As far as translating the expression I would like to make something that comes close to matching as much as possible.  If can't figure it out then default hash code to 0 (Essentially use the 3.0.1 system), or if parts can't be figured out use the ones that can be and still have less to search through.

I'm willing to do the expression translation to property conversion to get hash codes that will be as close to possible having a one to one comparison.  If you want to give me examples of what to expect comparison wise I can look into making as many of them work as best they can.

**Comment by Tasteful** [comment]
Now the code is updated (again) and now we only have one EquivalentExpression that will handle both situations including mapping from EF.

To expand the function to work with more equality expressions it is the `AutoMapper.EquivalencyExpression.EquivalentExpression<TSource, TDestination>.MemberExpressionExpando` that need to be modified.

Right now it is expanding and mapping correctly with hashcode if single or multiple equals expression. Negative expressions is not handled.

Also added option in the `CollectionMapper` extension method to set if the mapping should throw exception if not efficient mapping can be created (default: false).

As you can see in the test some of the tests are taking longer time, thats because the mapping is not efficient due to negative or or-conditions and going back to the `3.0.1`-mode.
image

**Comment by Tasteful** [comment]
I updated the `IEquivalentExpression<TSource, TDestination>` with an extra method to been able to have the Mapping-method inside `EquivalentExpression` itself. This is a breaking change but I don't think anyone is implementing that in their project, they can't add it to the private `EquivalentExpressions._equalityComparisonCache` either so I don't think this is a problem.

**Comment by TylerCarlson1** [comment]
I don't know about the True/False for performance throwing exception.  Maybe if it was an enum instead of a bool that could better explained what you are setting.

I would think Map should be outside `IEquivalentExpression<TSource, TDestination>` since it's getting equivalency and not actually doing the maps.  The Map code and the translation shouldn't have to be redefined if they make their own instance.  And then you would expose the GetHashCode methods for both the source and destination type in interface, and maybe update the interface name to better represent what it does  Maybe just IEquivalent or IEquivalentComparer instead of IEquivalentExpression.

**Comment by Tasteful** [comment]
The 
> True/False for performance throwing exception

is applied when the mapping expression is created, to be able on an easy way to see if an mapping can efficient be performed. This is probably a setting that should be per mapping in that case, otherwise it is hard to override that for a specific mapping. I will remove that flag.

Maybe `ICollectionMapper`.

The `EquivalentExpression` is not an `Expression` so that should probably be renamed also.
The `EquivalentExpressions._equalityComparisonCache` is private so it is today impossible to add own mapper implementation without rewriter larger parts.

**Comment by TylerCarlson1** [comment]
Maybe there's a better place for the flag.  I would want an enum so it's more explicit what it actually does.

I would still want the Map logic in `CollectionMapper` and not EquivalentExpression, even if there's no way to easily change the code.  `CollectionMapper` maps the collection by insert/update/delete using `GetHashCode(TSource)`, `GetHashCode(TDest)` and `IsEquivalent(TSource, TDest)` from `IEquivalentComparer` using dictionary to help speed up the process.

`IEquivalentComparer` and `EquivalentComparer` seem like the best names, because they best match `IEqualityComparer` interface, just with 2 classes instead of a single one, and an expression as well as a compiled function of it.

**Pull request closed without merging**
