### PR TITLE
EFCore version of the AM.collection

### PR DESCRIPTION
**Pull request by Tasteful**
EFCore version of the EntityFramework package including tests and updated readme.

#86 

Todo:
- [x] Allow DbContext to be contructed from DI to not require an empty ctor.

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
I'm wondering if these EF and EFCore and LinqToSQL projects need to be in their own Repos.  Because updating all when change to any.  Especially EFCore because it's more likely to change than the rest

**Comment by Tasteful** [comment]
I think the versioning is the major part that differ if they should be in one or multiple repositories. If they should have independent release life-cycle it can be a good idea to split them up in multiple repositories, if they anyway will be shipped on the same time it is easier to maintain everything together.

If we check history on the EF and LinToSQL project it is more or less static code (it was long time ago it was any changes there) and that can be a reason to split all the extra ORM mappers out into own repositories to avoid pushing new versions of that packages even that it does not contains any changes.

**Comment by TylerCarlson1** [comment]
That's my point exactly with EF and LinqToSQL.  They are just simple extensions that just make conventions that never change.  EFCore will have different release cycles than Collection as well.  I think it will have more to do with upgrading the reference to EFCore than anything else, while Collections only needs to be updated when AM updates to a big version, or newer versions cause issues.

**Comment by Tasteful** [comment]
@TylerCarlson1 Can you setup new repositories configured with the appveyor hook?

Then I can cleanup projects and and prepare PRs with the changes.

**Comment by TylerCarlson1** [comment]
@jbogard Are all repositories under AutoMapper have the AppVeyor hook by default or do I have to do something for them?

**Comment by jbogard** [comment]
The easiest thing to do is open a PR with WIP in the title

**Comment by TylerCarlson1** [comment]
https://github.com/AutoMapper/AutoMapper.Collection.EFCore
Might have to copy Tools to get it to build.
I'll need to look into creating the build hook again in AppVoyer.  It's coming back to me bit by bit now.
@Tasteful give it a shot

**Comment by Tasteful** [comment]
Closing this for
https://github.com/AutoMapper/AutoMapper.Collection/pull/106
https://github.com/AutoMapper/AutoMapper.Collection.EFCore/pull/1

**Comment by Tasteful** [comment]
@TylerCarlson1 If you setup new repositories for the EF and Linq2Sql I can prepare them also with a new PR

**Comment by TylerCarlson1** [comment]
I'll try to get that done some time this week.  Probably after we get EFCore set up correctly in myget.

**Pull request closed without merging**
