### PR TITLE
Hashing expressions

### PR DESCRIPTION
**Pull request by TylerCarlson1**
@Tasteful This is what I was going for with #42.  If there's no matching expressions, then will default hash set to 0 and the removing from list when find match will work just like 3.0.1 since the dictionary will only have one entry with all the items in it.

I also took out the added ExpressionMap called, because I think expression reading can handle those.
Second commit I removed the clearing of the expression cache, because even if it's partial it will help speed things up.
Ex: Can't extract negative test is now is faster, because half of it can be used for hashing even though the other one can not.  The negative can't help but because of the && the equals has to be always true for a match so can use it for hash filtering.

The idea is to further improve getting correct, complete or partial expressions lists to help speed up with hash set.  I'll look at making more examples like the ones you had in #42 and see if I can't improve the supported hashing function scenarios.

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
@Tasteful Any other expressions you are worried about translating?  Or only including translation in general vs making a new method call?

**Comment by Tasteful** [comment]
@TylerCarlson1 I haven't have time to check any more expressions, I will do that in the next few days. I found a memory leak bug in entity framework core that I need to spend more or less all my time on.

**Comment by TylerCarlson1** [comment]
@Tasteful That's fine I don't need the performance increase right away.  Can get to it later

**Comment by Tasteful** [comment]
I tested this version in my real life application that I'm working with and got this performance boost, I only switched the DLL so everything is fully backward compatible.

```txt
Inventory items contains 36 000 rows - version 3.0.0
2017-06-29 09:50:03.2045 - Update inventory 8f565396-90c0-4c97-ab13-24e04ac95252 
2017-06-29 09:50:42.6848 - Updated inventory 8f565396-90c0-4c97-ab13-24e04ac95252 

current development version
2017-06-29 09:55:01.0867 - Update inventory 8f565396-90c0-4c97-ab13-24e04ac95252 
2017-06-29 09:55:02.2771 - Updated inventory 8f565396-90c0-4c97-ab13-24e04ac95252 

current development version and also reverset the items collection
2017-06-29 09:57:00.8912 - Update inventory 8f565396-90c0-4c97-ab13-24e04ac95252 
2017-06-29 09:57:02.0260 - Updated inventory 8f565396-90c0-4c97-ab13-24e04ac95252 
```

The complex mapping I have is the following.
```c#
.EqualityComparison((a, b) => a.RelationshipTypeSystemId == b.RelationshipTypeSystemId &&
    (a is BaseProductToBaseProductRelationshipLink && ((BaseProductToBaseProductRelationshipLink)a).BaseProductSystemId == b.ToSystemId
    || a is BaseProductToCategoryRelationshipLink && ((BaseProductToCategoryRelationshipLink)a).CategorySystemId == b.ToSystemId
    || a is BaseProductToVariantRelationshipLink && ((BaseProductToVariantRelationshipLink)a).VariantSystemId == b.ToSystemId))
```
I think we cover that scenario with test [Should_Be_Fast_With_Large_Lists_SubObject](https://github.com/AutoMapper/AutoMapper.Collection/pull/45/files#diff-27ca0db038f31a544532c5454917ae40R135)

I think we can :shipit:

**Comment by TylerCarlson1** [comment]
Ok I'll try to get this out by the end of the day or tomorrow.  I'm thinking 3.1.0 since no API changed, but it's a bigger change.

**Pull request merged**
