### PR TITLE
Upgrade to AutoMapper 11

### PR DESCRIPTION
**Pull request by jbogard**

### CODE REVIEW

**Comment by jbogard** [comment]
Fixes #164

**Comment by lbargaoanu** [comment]
So many users and nobody could be bothered to do _this_? You gotta love open source :) I thought it's a huge undertaking or smth.

**Comment by jbogard** [comment]
Ha! It does make me want to move to monorepo, updating all of these is a pain.

**Comment by ChrisJollyAU** [comment]
Thanks @jbogard . I had previously looked at this and worked out the functions to .Internal() but had yet to sort out the object changes (e.g. IConfigurationProvider to IGlobalConfiguration, IConfigurationObjectMapper to IObjectMapper)

Was thinking about looking at it this weekend but clearly don't have to anymore

**Pull request merged**
