### PR TITLE
[WIP] 5.3 compatible

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Mappers list logic is changed in 5.3 of AutoMapper.  This fixes that issue.

Also refactored how add EF and LinqToSQL will work with AM.Collection so that you have to call everything on initialize once instead of after mapper.

Right now it's currently only supports one static instance.  Will need to allow to work with multiple IMapper objects.

### CODE REVIEW

**Comment by squirmy** [comment]
@TylerCarlson1 any chance this could be added to MyGet?
http://myget.org/gallery/automapperdev

A few issues have been fixed in 5.3, and i'm finding it difficult to upgrade as i'm using AutoMapper.Collection.

**Comment by TylerCarlson1** [comment]
I'll have to talk to @jbogard about this.  I'm not sure how to set up the build server myself.

**Comment by TylerCarlson1** [comment]
@squirmy It's on there now but just AM.Collections  I need to do some more work to add EntityFramework and LinqToSql because they need to reference the auto generated number of the pre-release for them to all work together.

**Comment by squirmy** [comment]
@TylerCarlson1 nice work! I'll check it out. Thank you! 👍

**Comment by TylerCarlson1** [comment]
AM.Collection.EF and AM.Collection.LinqToSQL are both in MyGet feed referencing the AM.Collection.

**Pull request merged**
