### PR TITLE
Avoid circular lookups with usage of FindTypeMapFor instead of ResolveTypeMap

### PR DESCRIPTION
**Pull request by Tasteful**
This is a failing test for https://github.com/AutoMapper/AutoMapper.Collection.EFCore/issues/13

### CODE REVIEW

**Comment by Tasteful** [comment]
Ping @jbogard @TylerCarlson1

**Comment by TylerCarlson1** [comment]
I see how it bypasses the circular reference but what I think might happen is that collection mapper won't work properly when you use `CreateMissingTypeMaps=true`, which this test doesn't prove.

The issue I see is when using FindTypeMap it has to be cached as an available type map that's been configured, but with conventions `Contact` to `ContactViewModel` won't be generated in the `_typeMapRegistry` when checking the `Systems` map and will skip out on `AutoMapper.Collection` functionality.  That's why `ResolveTypeMap` is used instead of `FindTypeMap`, because of `Conventions`/`CreateMissingTypeMaps` will have to attempt to  generate the child `TypeMap` before it can be determined if it can use `AutoMapper.Collection` functionality.

**Comment by Tasteful** [comment]
In what cases will we have `IEquivalentComparer` registered for the type if we not explicit register the type? If we not have the `IEquivalentComparer` registered it should anyway not result in any comparison except if the `IGeneratePropertyMaps` is registered and can handle the type.

For at least EF/EFCore I think it possible to change the code so the mapping is fetched and registered during the configuration (`cfg.SetGeneratePropertyMaps<T>()`) and all mappings will then already exists. For the Linq2Sql extension; as I understand it, we also have a `DataContext` and an model (`dbml`-file) so we should probably be able to do the same there.

Is it any other case that I'm missing?

**Comment by TylerCarlson1** [comment]
I think the main/only case is when `CreateMap` isn't specifically called and Convention will both create a new map on the fly, and `IGeneratePropertyMaps` will want to generate a comparison is where this will fail.

If I understand what you are saying I don't think you can do it on `cfg.SetGeneratePropertyMaps<T>()` because for conventions they won't be known until you actually use them for the first time.  So for configuration you would have to provide some sort of configuration option that would use reflection to go through and do all the comparisons at run time, but ignore certain aspects in order to cut down on time scanning.  Otherwise it would scan all enteties in DataContext with every class Type imaginable on startup.

Maybe I'm understanding your possible solution wrong, but circular references have always been a big problem, which is why the recommended option is don't do them in the first place.  Another option is to store which types are being used so that if they come back to it in a circular reference like this, then skip.  Or try catch and if get this exception return can't compare meaning you can't use AM.Collection functionality in a circular manner.

**Comment by Tasteful** [comment]
If we checking the inbuilt `CollectionMapper` that we have in AM (that we also falling back to in some cases) the `IsMatch` method is only checking if the type can be converted with the `IObjectMapper`, in the method `MapExpression` the `ResolveTypeMap` is used and seams to not throw circular reference issue. In `EquivalentExpressionAddRemoveCollectionMapper` we have we are calling the `ResolveTypeMap` already in the `IsMatch`, if we move the logic from that method into the `MapExpression` method and in the `IsMatch` method only check if we have any `IGeneratePropertyMaps´ method that can handle the type I think we can get it to work.

To you have possibility to provide a test-case for the usage that need to have the _Convention_ to create/map on the fly?

**Comment by TylerCarlson1** [comment]
I think with your existing test you can just modify the map and asserts to prove it's not using AM.Collection logic.

If this doesn't cause the test to fail, then maybe I missed something and will need to check it out more thoroughly
```
var model = new SystemViewModel
{
    Name = "My First System",
    Contacts = new List<Contact>
    {
        new Contact
        {
            Name = "John",
            Emails = new List<Email>()
            {
                new Email
                {
                    Address = "john@doe.com"
                }
            }
        }
    }
}
var originalEmail = model.Contacts.Single().Emails.Single();
mapper.Map<SystemViewModel>(system, model);
// This tests if equality was found and mapped to pre-existing object and not defaulting to AM and clearing and regenerating the list
model.Contacts.Single().Emails.Single().Should().Be(originalEmail);
```

**Comment by Tasteful** [comment]
@TylerCarlson1 You are correct, it is falling back to the default collection mapping in this case, updated the test to also cover this.

@lbargaoanu The https://github.com/AutoMapper/AutoMapper/issues/2987 is still a problem, it seams that we not can use the `FindTypeMapFor` in this case when the `TypeMap` does not exists and need to be generated upfront during the `IsMatch` check to see if the `IObjectMapper` can be used..

**Comment by Tasteful** [comment]
#125 is a replacement for this.

**Pull request closed without merging**
