### PR TITLE
Build and deploy signed version

### PR DESCRIPTION
**Pull request by Tasteful**
- Update the csproj-file to easier produce the signed version.
- Update build-script to produce signed version

### CODE REVIEW

**Comment by Tasteful** [comment]
@TylerCarlson1 have you think anything about this PR? If possible that will help so MS ISV that need to sign assemblies can use it directly withou maintain own version.

**Comment by TylerCarlson1** [comment]
I was thinking about throwing this in after the expression thing gets done then release

**Comment by jbogard** [comment]
FYI you can use the NuGet package StrongNamer in the meantime
https://github.com/dsplaisted/strongnamer as no new OSS packages should be
strong named.

**Comment by Tasteful** [comment]
@jbogard I don't agree with you about if OSS packages should be strong named or not. If you look at your own AutoMapper you was adding the strong name signing back after testing to remove it in some release. If you see all the new packages that MS is releasing for .net core they are strong name signed and they can only use other strong name signed package (as you already know). To have the package strong name signed you have more developers that directly can use the package and not need to create their own version. We should not start the debate that always threads like this will end in...... so final comment about that.

For me as working for a company that is MS ISV we need to strong name and digitaly sign our packages with authenticode certificates, we can only use other packages that are strong name signed. For this package I manage our own strong name signed version but it is extra effort to hold that up to date and not miss any improvements that is important or get our partner to user the correct package to not break their installations. To get the strong named version directly from the OSS project is a big help for that.

**Comment by Tasteful** [comment]
@TylerCarlson1 was you able to push the signed-package to nuget.org also?

**Comment by jbogard** [comment]
The recommendation from MS itself is to not sign new packages, as it's a
technically useless virus. StrongNamer fixes anyone that is still forced to
sign.

**Comment by Tasteful** [comment]
@jbogard I don't have a problem because I can sign and publish the package by myself. The only thing is that it is easier if the package author (the one that make new releases) publish all type of packages so the version number is in sync with each other and all the different packages will be released at the same time. 

The biggest thing is that all package will end up multiple times on ex nuget.org, one for unsigned and one for signed of not the "main" package is signed.

Strong name signed assemblies is the only way you can handle versionning, so you can apply a patch globaly on a server that have hundreds installation that is using an assembly without changing each installation, or restrict that your application is only working for a range of versions.

We can see other package authors that is going other way around and strong name sign their main package and drop the extra package example https://github.com/StackExchange/StackExchange.Redis/issues/545 

Also see the discussion here discussion here https://github.com/aspnet/DataProtection/issues/245 and as @davidfowl is writting here https://github.com/aspnet/DataProtection/issues/245#issuecomment-307155485 is that the StrongNamer is for consumer, not producers so that tool will not help in any way to produce the strong name assemblies for a package producer. 

If the a package producer need to strong name sign the package also the dependencies need to be strong name signed. If that strong named package will be the package author that deploy that package or someone else dosen't matter.

Then I'm also intressting for the official Microsoft announcement for
> The recommendation from MS itself is to not sign new packages, as it's a
technically useless virus. StrongNamer fixes anyone that is still forced to
sign.

**Comment by jbogard** [comment]
Oh, no don't publish multiple packages to NuGet, signed and unsigned,
that's also a mistake. Just publish an unsigned version, and those that are
forced to consume a signed version can use StrongNamer.

.NET Core doesn't even honor strong naming, it's only in MS assemblies for
legacy reasons. I'll dig up their recommendation to me (this came up on
MediatR so I reached out to the .NET team for their advice)

**Comment by Tasteful** [comment]
@jbogard How can I distribute the package to hundreds of other developers without publishing the strong name signed package?

**Comment by Tasteful** [comment]
@jbogard from https://msdn.microsoft.com/en-us/library/h4fa028b(v=vs.100).aspx
> What Should Be Strong-Named
Shared DLLs should be strong-named. Regardless of whether a DLL will be deployed to the Global Assembly Cache, a strong name is recommended when the DLL is not a private implementation detail of the application, but is a general service that can be used by more than one application.

**Comment by jbogard** [comment]
That's old, here's the current guidance:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

.NET Core doesn't honor the same rules as full .NET, to avoid DLL hell and diamond dependencies forcing binding redirects for 99% of usages. If you're in a situation where you're *forced* to SN (because you *have* to install to the GAC for example), then I could see you having to SN. I wouldn't ask upstream packages to introduce SN'ing tho - that's a breaking change as is removing a SN (my mistake). Instead, I'd look at adding the SN as part of my build and packaging. Years ago that's what I did in AutoMapper - signed a 3rd party assembly, internalized it and ILMerge'd.

You're distributing a VSIX? Is that the deal?

**Comment by Tasteful** [comment]
We are distributing an ecommerce application (nuget packages) that is taking dependencies on a lot of external packages. The ecommerce application is certified for Windows Server and for that certification the dll's need to be strong name signed (MS process) and also authenticode signed. When the developers from our customer or partner is developing they need to download the same version of package that we are using, thats the reason we cant us StrongNamer to get a strong named version that we compiled with without distributed that as a dependency package.

And asking if an upstream package can SN is only a question, and the author can say now but they can not blame anyone else then they self if the package will be SN by someone else and published on a public feed like nuget.org so that contains multiple packages for the same purpose.

Are you thinking about SN'ing if MS is creating an issue about SN'ing to be able to use the package in say the default ASP.NET MVC template?

**Comment by jbogard** [comment]
Are you saying someone would sign the package and re-publish? NuGet team would take that package down.

If I were you, I'd ILMerge and sign the whole thing, regardless. If you're depending on all your dependencies to be SN'd (which can be removed at any point by the OSS authors), I'd make sure that it wouldn't matter. What would you do if for example I took away the AutoMapper SN?

**Comment by Tasteful** [comment]
if AutoMapper lose the SN we will either stay on a version that still have SN or replace with something else.

And if you take a look at example https://www.nuget.org/packages?q=lucene.net&page=2 you can see that it exists a lot of different packages that are "lucene.net" but with different names so i'm not sure that nuget team would take that package down.

**Comment by Tasteful** [comment]
And both AutoMapper and AutoMapper.Collection is using the MIT license that allow anyone to republish it with a new name if they need.

**Comment by jbogard** [comment]
Do you have a link to the docs from MS on certifying for Windows Server that it requires SN'ing?

It's just....so incredibly OSS-hostile to force OSS package authors to strong name when strong naming is so user-hostile.

**Comment by jbogard** [comment]
And those multitude of package names - hopefully not for long https://github.com/NuGet/Home/wiki/NuGet-Package-Identity-Verification as I want to fold "blessed" extensions for example all under the AutoMapper org umbrella.

**Comment by Tasteful** [comment]
See point 3.1 on https://msdn.microsoft.com/en-us/library/windows/desktop/mt674655(v=vs.85).aspx

**Comment by jbogard** [comment]
Uhhhhh https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/AssemblyInfo.cs#L8

**Comment by jbogard** [comment]
That doesn't say "you must strong name" tho?

**Comment by Tasteful** [comment]
but it says `to ensure secure access to strong-named assemblies` and you will only have that validation if you also is using SN.

**Comment by jbogard** [comment]
Eh? Not-strong-named assemblies can access strong-named ones. The opposite is *not* true, you can't access not-strong-named assemblies from strong-named ones.

**Comment by Tasteful** [comment]
- If you haven't an strong named assembly you can't secure the access to other assemblies because the strong name is not checked.
- If you have an strong named assembly you can only use strong named assemblies and the strong name is checked.

**Comment by jbogard** [comment]
That seems completely at odds with the MS guidance that "strong-naming isn't for security"

**Comment by jbogard** [comment]
From https://twitter.com/terrajobst/status/880836796556300288 @terrajobst

**Comment by Tasteful** [comment]
Then it is strange that we was needing to SNing when we was applying for the certification many years ago. And we can't remove the SNing on our assemblies either because of breaking of all current installations.

**Comment by TylerCarlson1** [comment]
Just so you know I'm still having troubles getting Master Tag Branching to push to Nuget.org from appvoyer build.  The myget it working fine for development branch.  I just built and pushed AM.Collections manually for right now.

So there isn't a AM.Collections Signed in Nuget atm.

**Comment by jbogard** [comment]
Hmmmm looks like MS *does* recommend package authors strong name:

https://github.com/aspnet/DataProtection/issues/245#issuecomment-307155485

So while there's no real technical benefit to SN, it introduces a technical limitation for you.

+1 on strong naming then!

**Comment by Tasteful** [comment]
@jbogard do you mean to SN the main package or a separate package?

@tylercarlson1

**Comment by TylerCarlson1** [comment]
I'm not sure about all this Strong Naming, as I don't have a need for it.
I would prefer to keep strong named separate since the original is not and you have something that can strong name it if you want.

@Tasteful it was more giving you the things you require for your use case and making it easier for you.
It might be stupid reasons why you need it, but you still **need** it regardless.
I can push the signed manually as a different name, or if you are already doing that it's easier for you.  Or if I can figure out why AppVoyer isn't triggering the the Nuget push can do that as well.

**Comment by jbogard** [comment]
@Tasteful SN the main package. Separate packages are....bad. SE.Redis is going SN'd for the main one and removing/obsoleting the SN-specific package https://github.com/aspnet/DataProtection/issues/245#issuecomment-307097403

**Comment by TylerCarlson1** [comment]
If that's the case maybe that makes more sense because AM is SN.  And I would guess EF6 is SN as well so that shouldn't be a problem for the other ones.

I just hope that this doesn't get flipped flopped around in a few months.

**Pull request merged**
